[EMERGENCY] f* you workflow!!!

diff --git a/.github/workflows/Publish.yaml b/.github/workflows/Publish.yaml
--- a/.github/workflows/Publish.yaml
+++ b/.github/workflows/Publish.yaml
@@ -37,7 +37,7 @@ jobs:
         run: |
           extensionFileName=soberjs-vscode-${{ needs.build.outputs.extension-version }}.vsix
           echo "extensionFileName=$extensionFileName >> $GITUHB_ENV"
-          unzip ${extensionFileName}.zip || echo "Fail, but we'll continue!"
+          unzip "$(ls -1 /home/runner/work/soberjs-vscode/soberjs-vscode/*.zip)" || echo "Fail, but we'll continue!"
       - name: Publish to Visual Studio Marketplace
         uses: HaaLeo/publish-vscode-extension@v1
         if: ${{ ! inputs.prerelease }}
